# Generated by Django 4.2.6 on 2023-10-18 23:17

from django.db import migrations, models
import django_countries.fields
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('sexo', models.CharField(choices=[('F', 'Femino'), ('M', 'Masculino')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('data_nascimeto', models.DateField()),
                ('nacionalidade', django_countries.fields.CountryField(max_length=2)),
                ('cpf', django_cpf_cnpj.fields.CPFField(max_length=14, unique=True)),
            ],
        ),
    ]
