# Generated by Django 4.2.6 on 2023-10-21 23:46

from django.db import migrations, models
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arte', '0002_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='autores',
            field=models.ManyToManyField(blank=True, null=True, related_name='obras', to='arte.autor'),
        ),
    ]
