# Generated by Django 4.2.6 on 2023-10-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arte', '0003_alter_autor_cpf_alter_obra_autores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='data_de_exposicao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='data_de_publicacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
