name: obras App

on: [pull_request]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
                - uses: actions/checkout@v4
                - name: set up python
                  run: pipx install poetry
                - uses: actions/setup-python@v4
                  with:
                    python-version: '3.11'
                    cache: 'poetry'

                - name: instalar dependencias
                  run: poetry install --with dev

                - name: lint
                  run: poetry run task lint

                - name: testes
                  run: |
                    cp contrib/env-sample .env
                    poetry run task test