name: obras App

on: [pull_request]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
                - uses: actions/checkout@v4
                - name: set up python
                  uses: actions/setup-python@v4
                  with:
                    python-version: '3.11'
                    architecture: 'x64'
                - name: instalar dependencias
                  uses: poetry install

                - name: lint
                  uses: task lint